# jpegoptim --strip-all --verbose --size=60% --max=70 --totals ./public/images/andrew_patriarchs.JPG
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/walk_in_the_park.jpg
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/hole_in_the_wall.jpg
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/zion_observation.jpg
# jpegoptim --strip-all --verbose --size=70% --max=80 --totals ./public/images/christmas_tree.JPG
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/dino_hunt.jpg
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/surgery.JPG
# jpegoptim --strip-all --verbose --size=70% --max=30 --totals ./public/images/bad_news_broken.JPG
# jpegoptim --strip-all --verbose --size=70% --max=60 --totals ./public/images/metal_texture.jpg
# jpegoptim --strip-all --verbose --size=25% --max=70 --totals ./public/images/engaged_with_butterflies.JPG
# jpegoptim --strip-all --verbose --size=25% --max=70 --totals ./public/images/fancy_pose.jpg
